# This is a basic workflow to help you get started with Actions

- name: install.node JS
        uses:actions/setup-node@v2-beta
        with:
            node-version: 12
      # Runs a set of commands using the runners shell
      - name: GitHub Action for Yarn
       # You may pin to the exact commit or the version.
        # uses: Borales/actions-yarn@4965e1a0f0ae9c422a9a5748ebd1fb5e097d22b9
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Creating build
        run: sudo npm run build
      - name: installing surge 
        run: sudo npm install --global surge
      - name: deploying on surge 
        run: surge ./build http://niazian.surge.sh/ --token ${{secrets.MY_SURGE_TOKEN}}
