# This is a basic workflow to help you get started with Actions
name: Installing NodeJSS
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.0.0
      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1

      - name: installing surge 
        run:  npm install --global surge
      - name: deploying on surge 
        run: surge ./build http://niazian.surge.sh/ --token ${{secrets.MY_SURGE_TOKEN}}
